### ISSUE TITLE
Extension does not seem to recognize Hugo site

### ISSUE THREAD

**Issue by balaji-dutt** [willofindie/vscode-gohugo#3]
Hi,

I'm a little confused on how to get the extension to work with my local Hugo environment. 

**Extension version:** 
``` 
0.1.0
```

### My Environment

- Windows 10 Professional x64
- VSCode 1.58.2

### Expected Behavior
* When I run the command `gohugo: Start Server`,  the command should launch a local hugo server. 
* When I run the command `gohugo: Create New Content`, the command should place an empty post file

### Actual Behavior
* When I run the command `gohugo: Start Server`, navigating to `localhost:1313` results in a "Site cannot be reached error"
* When I run the command `gohugo: Create New Content`, no file is created

### Steps to reproduce the problem:
Steps to reproduce:
- Install the extension from VSCode Marketplace. Ensure the extension settings are as follows:
![Code_h160ySu1gO](https://user-images.githubusercontent.com/3147070/127423660-d229df3c-ac8b-40aa-b973-ef0330b4bafd.png)
- Create a VSCode workspace and add the folder with the Hugo site to the workspace.
![MOYIUPS3EU](https://user-images.githubusercontent.com/3147070/127423865-9dc4caae-ee71-4a2a-97ed-c9a329984b69.png)
- Verify that `config.toml` exists in the root of the folder and has the following configuration:
``` toml
baseurl = "https://myblog.domain.tld"
DefaultContentLanguage = "en"
title = "My Hugo Blog"
theme = "beautifulhugo"
contentDir = "content"
languageCode = "en-us"
```
- Run the command `gohugo: Start Server`. The following Terminal window appears:
![Code_xELL6NSyri](https://user-images.githubusercontent.com/3147070/127423964-20e573a2-2a51-4368-b073-da91cd9832ac.png)
